apiVersion: kustomize.config.k8s.io/v1beta1
kind: KustomizeConfig
metadata:
  name: kube-state-metrics
  namespace: monitoring
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - kind: HelmRelease
    path: spec/valuesFrom/name
