apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 10m
  path: ./kube-state-metrics
  prune: true
  sourceRef:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
   
