apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 10m
  url: https://kubernetes.github.io/kube-state-metrics
  
